### ISSUE TITLE
Запоролись названия чанков

### ISSUE THREAD

**Issue by glebmachine** [TinkoffCreditSystems/shared-library-webpack-plugin#20]
Привет, вот тут ты переписываешь названия чанков красивые просто хешом
Кажется, что посольку везде в доках они красивые, а на практике просто хеши - то это баг)

https://github.com/TinkoffCreditSystems/shared-library-webpack-plugin/blob/55db3f3791da38d63e89b040bcb71c2181dcd9e9/libs/shared-library-webpack-plugin/src/lib/shared-library-webpack-plugin.ts#L715

**Comment by IKatsuba** [comment]
Привет. Я бы конечно не называл это багом, так как это ожидаемое поведение. Но в рамках этого issue подумаю как вернуть красивые имена. Либо поправлю доки.

**Comment by glebmachine** [comment]
@IKatsuba понял тебя, как вариант - дев/прод режим разделить
В дев режиме очень удобно понимать что конкретно грузится (для отладки и в целом осознания что где)

А в боевом можно их названия еще подрезать по длине хэша до 7 символов, чтобы были аккуратненькие названия)

**Comment by IKatsuba** [comment]
@glebmachine думал примерно о том же. Обязательно сделаю что-нибудь такое. Спасибо за фидбэк!
